/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        "3xl": "1920PX",
        // print: { raw: "print" },
      },
      gridTemplateRows: {
        twoRows: "80px 1fr",
        threeRows: "56px 1fr 56px",
        twoRowsReverse: "1fr 44px",
      },
      gridTemplateColumns: {
        layout: "240px 1fr",
      },
      backgroundImage: {
        sbanner: "url('/gallery/sbanner.jpg')",
        shapeOne: "url('/shape/ShapeOne.png')",
        shapeTwo: "url('/shape/ShapeTwo.png')",
        shapeThree: "url('/shape/ShapeThree.png')",
        shapeFour: "url('/shape/ShapeFour.png')",
        shapeRed: "url('/icons/red.png')",
        shapeRocket1: "url('/icons/1.png')",
        shapeRocket2: "url('/icons/2.png')",
        shapeRocket3: "url('/icons/3.png')",
        shapeRocket4: "url('/icons/4.png')",
        shapeRocket5: "url('/icons/5.png')",
        shapeRocket6: "url('/icons/6.png')",
        shapeRocket7: "url('/icons/7.png')",
        aboutBg: "url('/gallery/background.jpeg')",
      },
      colors: {
        primary: "#273238",
        primarydark: "#20292e",
        secondary: "#eaedf7",
        success: "#19b159",
        danger: "#f16d75",
        info: "#01b8ff",
        warning: "#ff9b21",
        darker: "#111827",
        dark: "#1f2937",
        lighter: "#f3f4f6",
        light: "#e2e4e8",
        orange: "#ff7722",
        yam: "#CC5801",
      },
    },
  },
  variants: {
    extend: {
      transitionProperty: ["hover", "focus"],
      transitionDuration: ["hover", "focus"],
      transitionDelay: ["hover", "focus"],
      animation: ["group-hover", "hover", "focus"],
      fontWeight: ["hover", "focus"],
      display: ["group-hover"],
      opacity: ["group-hover"],
      translate: ["active", "group-hover", "hover", "focus"],
      transform: ["group-hover", "hover", "focus"],
      width: ["group-hover", "hover"],
      height: ["group-hover", "hover"],
      padding: ["group-hover", "hover"],
      scale: ["group-hover", "hover"],
      backgroundColor: ["checked", "odd", "even"],
      borderColor: ["checked"],
      borderWidth: ["hover", "focus"],
    },
  },
  plugins: [],
};
